import json

with open('src/i18n/locales/en.json', 'r', encoding='utf-8') as f:
    en = json.load(f)

new_keys = {
    "about_p1": "Rwanda EasyRent is a modern property rental platform designed specifically for the Rwandan market. We connect property owners with tenants looking for their perfect home across all provinces of Rwanda.",
    "about_p2": "Our mission is to make property rental in Rwanda transparent, efficient, and accessible to everyone. Whether you are a property owner looking to list your properties or a tenant searching for a new home, EasyRent provides the tools you need.",
    "about_p3": "We support three languages - English, Kinyarwanda, and French - making the platform accessible to all Rwandans.",
    "accepted_image_formats": "PNG, JPG, WEBP, JFIF up to 10MB each",
    "account_created": "Account created! Check your email to verify.",
    "added_to_favorites": "Added to favorites!",
    "all_marked_as_read": "All marked as read",
    "amenities_and_features": "Amenities & Features",
    "anonymous": "Anonymous",
    "approved": "Approved",
    "back_to_login": "Back to Login",
    "back_to_properties": "Back to Properties",
    "basic_information": "Basic Information",
    "bath": "bath",
    "bed": "bed",
    "booking_approved": "Booking approved",
    "booking_cancelled": "Booking cancelled",
    "booking_sent": "Booking request sent! The owner will be in touch.",
    "cancelled": "Cancelled",
    "check_email_reset": "Check your email for the reset link.",
    "click_to_add_more_images": "Click to add more images",
    "click_to_upload_images": "Click to upload images",
    "close": "Close",
    "closed": "Closed",
    "cms": "CMS",
    "commercial": "Commercial",
    "community": "Community",
    "community_desc": "Building a better rental ecosystem for all Rwandans.",
    "contact_failed": "Failed to send message. Please try again.",
    "contact_subtitle": "Have a question? We would love to hear from you.",
    "contact_success": "Message sent! We will get back to you soon.",
    "contact_support": "Contact Support",
    "continue_editing": "Continue Editing",
    "cottage": "Cottage",
    "current_images": "Current Images",
    "d_ago": "d ago",
    "data_and_images_lost_warning": "Any entered data and uploaded images will be lost.",
    "default_support_message": "Hello, I need help with something.",
    "deposit_placeholder": "Deposit amount",
    "deposit_rwf": "Deposit (RWF)",
    "description_placeholder": "Describe your property in detail - size, condition, surroundings, nearby amenities...",
    "discard_changes": "Discard Changes",
    "discard_changes_confirm": "Discard changes?",
    "duplicate_booking": "You have already sent a booking request for this property",
    "eastern": "Eastern",
    "edit_full_details": "Edit full details",
    "edit_property_details": "Edit property details",
    "enter_email_reset": "Enter your email and we will send you a reset link.",
    "enter_new_password": "Enter your new password below.",
    "failed_contact_support": "Failed to contact support",
    "failed_to_approve_booking": "Failed to approve booking",
    "failed_to_cancel_booking": "Failed to cancel booking",
    "failed_to_delete_notification": "Failed to delete notification",
    "failed_to_mark_as_read": "Failed to mark as read",
    "failed_to_remove_favorite": "Failed to remove favorite",
    "failed_to_remove_image": "Failed to remove image",
    "failed_to_submit_property": "Failed to submit property",
    "failed_update_favorites": "Failed to update favorites",
    "faq_subtitle": "Find answers to common questions about Rwanda EasyRent.",
    "featured_listings": "Featured Listings",
    "featured_listings_subtitle": "Hand-picked premium properties for you",
    "file_too_large": "File too large (max 10MB).",
    "furnished": "Furnished",
    "get_started": "Get Started",
    "h_ago": "h ago",
    "house": "House",
    "how_it_works_subtitle": "Three simple steps to find your perfect rental in Rwanda",
    "huye": "Huye",
    "image_issues": "Image issues:",
    "image_removed": "Image removed",
    "image_upload_failed": "Image upload failed",
    "image_upload_issues": "Image upload issues:",
    "innovation": "Innovation",
    "innovation_desc": "Modern technology to simplify the rental process.",
    "internet": "Internet",
    "just_now": "Just now",
    "kigali": "Kigali",
    "kitchen": "Kitchen",
    "kitchens": "Kitchens",
    "link_copied": "Link copied to clipboard!",
    "login_failed": "Login failed",
    "m_ago": "m ago",
    "manage_images": "Manage images",
    "musanze": "Musanze",
    "name": "Name",
    "newsletter_desc": "Stay updated with new properties.",
    "no_permission_to_edit": "You don't have permission to edit this property.",
    "no_support_staff": "No support staff available",
    "northern": "Northern",
    "nyagatare": "Nyagatare",
    "our_values": "Our Values",
    "pending_approval": "Pending Approval",
    "pending_booking_exists": "You already have a pending booking request for this property",
    "please_add_message": "Please add a message to the owner",
    "preferred_visit_date": "Preferred Visit Date",
    "price_placeholder": "Price amount",
    "price_rwf_month": "Price (RWF/month)",
    "pricing": "Pricing",
    "privacy_collect_desc": "We collect information you provide directly, such as your name, email address, phone number, and property details. We also automatically collect certain technical information about your device and usage.",
    "privacy_collect_title": "Information We Collect",
    "privacy_contact_desc": "If you have questions about this privacy policy, please contact us at privacy@rwanda-easyrent.com.",
    "privacy_contact_title": "Contact Us",
    "privacy_intro": "Your privacy is important to us. This policy outlines how we collect, use, and protect your personal information when you use Rwanda EasyRent.",
    "privacy_protection_desc": "We implement appropriate technical and organizational measures to protect your personal data against unauthorized access, alteration, disclosure, or destruction.",
    "privacy_protection_title": "Data Protection",
    "privacy_use_desc": "We use your information to provide and improve our services, communicate with you, process transactions, and ensure platform security and integrity.",
    "privacy_use_title": "How We Use Your Information",
    "profile_update_failed": "Profile update failed",
    "properties_found": "properties found",
    "property_created_image_issue": "Property created but some images may not have uploaded.",
    "property_images": "Property Images",
    "property_not_found": "Property not found",
    "property_published_successfully": "Property submitted successfully! It will be reviewed by our team.",
    "property_title": "Property Title",
    "property_title_placeholder": "e.g. Modern 2BR Apartment in Kicukiro",
    "property_updated_image_issue": "Property updated but some images may not display.",
    "quick_edit": "Quick edit",
    "ready_to_find_home": "Ready to Find Your Dream Home?",
    "ready_to_find_home_desc": "Join thousands of happy tenants and property owners across Rwanda. Start your journey today.",
    "remove_all": "Remove all",
    "remove_this_image": "Remove this image?",
    "removed_from_favorites": "Removed from favorites",
    "rent": "Rent",
    "rubavu": "Rubavu",
    "rwf": "RWF",
    "rwf_zero": "RWF 0",
    "sale": "Sale",
    "saved_to_favorites": "Saved to Favorites",
    "secure_platform": "Secure Platform",
    "secure_platform_desc": "Verified properties and secure transactions",
    "location_based": "Location Based",
    "location_based_desc": "Find properties in any province of Rwanda",
    "trusted_reviews": "Trusted Reviews",
    "trusted_reviews_desc": "Real reviews from real tenants",
    "studio": "Studio",
    "send_again": "Send again",
    "send_us_message": "Send us a message",
    "sent_reset_link_to": "We have sent a password reset link to",
    "set_your_price_and_deposit": "Set your price and deposit",
    "short_term": "Short-term",
    "southern": "Southern",
    "subject": "Subject",
    "submit_for_review": "Submit for Review",
    "submitting": "Submitting...",
    "subscribe_failed": "Failed to subscribe. Please try again.",
    "subscribed_success": "Subscribed successfully! Check your email.",
    "support_staff_message": "You are now connected with support staff.",
    "tell_owner_about_you": "Tell the owner about yourself and your interest...",
    "tell_us_about_your_property": "Tell us about your property",
    "terms_account_desc": "You are responsible for maintaining the confidentiality of your account and password. You must provide accurate, current, and complete information during registration.",
    "terms_account_title": "Account Terms",
    "terms_intro": "By using Rwanda EasyRent, you agree to these terms and conditions. Please read them carefully.",
    "terms_liability_desc": "Rwanda EasyRent acts as a platform connecting tenants and property owners. We are not party to any rental agreements and are not liable for any disputes arising from such agreements.",
    "terms_liability_title": "Limitation of Liability",
    "terms_listings_desc": "Property owners are responsible for the accuracy of their listings. All properties must comply with Rwandan laws and regulations. We reserve the right to remove listings that violate our policies.",
    "terms_listings_title": "Property Listings",
    "terms_payments_desc": "All payments are processed securely through our payment partners. We are not responsible for disputes between tenants and property owners regarding payments.",
    "terms_payments_title": "Payments",
    "testimonials_subtitle": "Hear from our happy customers",
    "today": "Today",
    "transparency": "Transparency",
    "transparency_desc": "Clear pricing, honest reviews, and open communication.",
    "trust": "Trust",
    "trust_desc": "We verify all properties and users to ensure a safe environment.",
    "try_adjusting_search": "Try adjusting your search or filter criteria.",
    "unknown_property": "Unknown Property",
    "unsaved_changes_are_you_sure": "You have unsaved changes. Are you sure you want to leave this page?",
    "unsaved_changes_lost": "Any unsaved changes will be lost.",
    "unsaved_changes_warning": "You have unsaved changes. Are you sure?",
    "unsupported_format": "Unsupported format. Use PNG, JPG, or WEBP.",
    "update_amenities": "Update amenities",
    "update_location": "Update location",
    "update_price_and_deposit": "Update price and deposit",
    "upload_photos_of_your_property": "Upload photos of your property",
    "verified_owner": "Verified Owner",
    "view_on_site": "View on site",
    "view_property": "View Property",
    "villa": "Villa",
    "welcome_back": "Welcome back! Sign in to your account.",
    "western": "Western",
    "what_does_your_property_offer": "What does your property offer?",
    "whatsapp": "WhatsApp",
    "whatsapp_number_optional": "WhatsApp Number (optional)",
    "whatsapp_placeholder": "e.g. +250788123456",
    "where_is_your_property_located": "Where is your property located?",
    "why_choose_us": "Why Choose Us",
    "why_choose_us_subtitle": "We make property rental simple, secure, and stress-free",
    "why_choose_us_title": "Why Rwanda EasyRent?",
    "working_hours": "Working Hours",
    "yesterday": "Yesterday",
    "your_email": "Your Email",
    "your_name": "Your Name",
    "zero": "0",
    "apartment": "Apartment",
    "faq1_q": "How do I create an account?",
    "faq1_a": 'Click on the Register button in the top right corner and fill in your details. You will need to verify your email address to activate your account.',
    "faq2_q": "How do I list a property?",
    "faq2_a": 'After registering as a Property Owner, go to your dashboard and click "Add Property". Fill in all the details, upload images, and submit for approval.',
    "faq3_q": "How long does property approval take?",
    "faq3_a": "Our admin team typically reviews and approves properties within 24-48 hours.",
    "faq4_q": "How do I book a property?",
    "faq4_a": 'Navigate to the property details page and click "Book Now". Fill in your details and the owner will be notified of your request.',
    "faq5_q": "How do I pay rent?",
    "faq5_a": "We support MTN MoMo, Airtel Money, Visa, and MasterCard payments through our secure payment gateway.",
    "faq6_q": "Is my data safe?",
    "faq6_a": "Yes, we use industry-standard encryption and security practices. Your personal information is never shared without your consent.",
    "faq7_q": "Can I switch between languages?",
    "faq7_a": "Yes! Click the language button in the header to switch between English, Kinyarwanda, and French at any time.",
}

en.update(new_keys)
print(f"Added {len(new_keys)} keys. Total: {len(en)} keys.")

with open('src/i18n/locales/en.json', 'w', encoding='utf-8') as f:
    json.dump(en, f, indent=2, ensure_ascii=False)

print("en.json updated successfully.")
